const express = require('express')
const routes = express.Router()
const userController = require ('../Controller/userController')
const examController = require ('../Controller/examController')
const zodMiddleware = require ('../MiddleWare/zodMiddleware')
const zodMiddleWareExam = require ('../MiddleWare/zodMiddleWareExam')
const { userSchemaValidation } = require('../Model/userSchemaValidation')
const { addExamSchemaValidation } = require('../Model/addExamSchemaValidation')
routes.post('/addUser',userController.addUser)
routes.get('/getUser',userController.getUser)
routes.get('/getOneUser/:Id',userController.getOneUser)
routes.post('/addExam/:Id',userController.addExam)
// routes.post('/addExamZod',zodMiddleWareExam.validate(addExamSchemaValidation),examController.addUser)
routes.post('/addExamzod/:Id',zodMiddleWareExam.validate(addExamSchemaValidation),examController.addExam)
routes.post('/checkUser',zodMiddleware.validate(userSchemaValidation),userController.addUser)
routes.put('/updateUser/:Id',userController.updateUser)
routes.delete('/deleteUser/:Id',userController.deleteUser)
routes.get('/getUserP',userController.popu)
module.exports = routes

